Import Libraries

In [22]:
from pyvis.network import Network
import networkx as nx
import random
from networkx.algorithms.community import greedy_modularity_communities
from networkx.linalg.modularitymatrix import modularity_matrix, directed_modularity_matrix
import numpy as np
from scipy.linalg import eig

Create Helper Functions

In [23]:
# recursive function that will traverse the nodes
def createPaper(network, authors, probStop):
    '''
    Will take network, list of authors, and probStop as input
    '''
    currAuthorID = authors[-1]
    newNeighbors = set(network.neighbors(currAuthorID)).difference(set(authors))

    # base condition: stop at node if probStop hit or there are no new neighbors to traverse
    if random.random() < probStop or len(newNeighbors) == 0:
        return
    
    # create list reprsenting probabilities for the neighboring nodes of the current coauthor
    probs = []
    for neighbor in newNeighbors:
        nData = network.get_edge_data(currAuthorID, neighbor)
        probs.extend([neighbor] * nData["weight"])

    # Select coauthor from neighbors probabilities list
    coauthorID = random.choice(probs)

    # update all edges of coauthors to this new author
    for author in authors:
        # if there is not an edge, create one
        if not network.has_edge(author, coauthorID) and author != coauthorID:
            network.add_edge(author, coauthorID, weight=0, width=1)
        newWeight = network.get_edge_data(author, coauthorID)["weight"] + 1
        #network.update(edges=[ (author, coauthorID, {"weight": newWeight, "width": newWeight//2}) ])
        network.update(edges=[ (author, coauthorID, {"weight": newWeight}) ])

    # call function recursively with coauthor
    authors.append(coauthorID)
    createPaper(network, authors, probStop)


Define initial parameters

In [24]:
# define time steps
timeSteps = 15

# Probabilities
# probability that you generate new author
probNewAuthor = 0.5
# probability that you stop at a given node
probStop = 0.7

# define fields
fieldColors = {"CS": "blue", 
                "Math": "green", 
                "Physics": "red"}
fields = list(fieldColors.keys())

# define initial scholars, will be in form (id, scholarField, color)
scholarField = random.choice(fields)
nodeID = 0


Create Model

In [25]:
network = nx.Graph()
scholarField = random.choice(fields)
network.add_node(nodeID, label=scholarField, color=fieldColors[scholarField])
# go through time steps, add new scholar and paper at each step
for i in range(1, timeSteps):

    # Choose first author, either new scholar or random choice
    currNodes = list(network.nodes())
    authors = [random.choice(currNodes)]

    # with probability, add new author to network set as main author with a coauthor
    if random.random() < probNewAuthor:
        # generate author and field
        scholarField = random.choice(fields)
        nodeID += 1
        author = nodeID
        network.add_node(author, label=scholarField, color=fieldColors[scholarField])

        # generate random coauthor from currNodes, which doesn't have the new node added in
        coauthorID = random.choice(currNodes)
        network.add_edge(author, coauthorID, weight=1, width=1)

        # update authors list
        authors = [author, coauthorID]

    # Add new paper, calling function
    createPaper(network, authors, probStop)

Display Network

In [26]:
nt = Network()
# populates the nodes and edges data structures
nt.from_nx(network)
print(network.edges.data())
nt.show('docs/models/modularity.html')

[(0, 1, {'weight': 1, 'width': 1}), (1, 2, {'weight': 1, 'width': 1}), (1, 3, {'weight': 2, 'width': 1}), (3, 4, {'weight': 2, 'width': 1}), (3, 5, {'weight': 1, 'width': 1}), (3, 6, {'weight': 1, 'width': 1}), (4, 6, {'weight': 1, 'width': 1}), (5, 7, {'weight': 1, 'width': 1}), (5, 8, {'weight': 1, 'width': 1}), (5, 9, {'weight': 1, 'width': 1})]


### Show modularity communities

In [27]:
communities = greedy_modularity_communities(network)
print(communities)
# look at exactly whay the matrix is calculating, make sure it is the unweighted
matrix = modularity_matrix(network)
print(matrix)

[frozenset({8, 9, 5, 7}), frozenset({0, 1, 2}), frozenset({3, 4, 6})]
[[-0.05  0.85 -0.05 -0.2  -0.1  -0.2  -0.1  -0.05 -0.05 -0.05]
 [ 0.85 -0.45  0.85  0.4  -0.3  -0.6  -0.3  -0.15 -0.15 -0.15]
 [-0.05  0.85 -0.05 -0.2  -0.1  -0.2  -0.1  -0.05 -0.05 -0.05]
 [-0.2   0.4  -0.2  -0.8   0.6   0.2   0.6  -0.2  -0.2  -0.2 ]
 [-0.1  -0.3  -0.1   0.6  -0.2  -0.4   0.8  -0.1  -0.1  -0.1 ]
 [-0.2  -0.6  -0.2   0.2  -0.4  -0.8  -0.4   0.8   0.8   0.8 ]
 [-0.1  -0.3  -0.1   0.6   0.8  -0.4  -0.2  -0.1  -0.1  -0.1 ]
 [-0.05 -0.15 -0.05 -0.2  -0.1   0.8  -0.1  -0.05 -0.05 -0.05]
 [-0.05 -0.15 -0.05 -0.2  -0.1   0.8  -0.1  -0.05 -0.05 -0.05]
 [-0.05 -0.15 -0.05 -0.2  -0.1   0.8  -0.1  -0.05 -0.05 -0.05]]


In [28]:
# get eigenvalues and vectors of matrix, maybe use scipy instead
eVals, eVects = np.linalg.eig(matrix)
# find indices of largest eigenvalue, get corresponding eigenvector
# if no positive eigenvalue, then cannot divide network further because it will not improve modularity
if max(eVals) > 0:
    index = np.argmax(eVals)
    maxEvect = np.array(eVects)[index]
    # split eigenvector into positive and negative values, collecting vertices
    g1 = []
    g2 = []
    for j, val in enumerate(maxEvect):
        if val < 0:
            g1.append(j)
            # test update the color
            network.update(nodes=[(j, {"label": "g1", "color": "green"})])
        else:
            g2.append(j)
            network.update(nodes=[(j, {"label": "g2", "color": "red"})])
# print(g1)
# print(g2)
print(eVals)


[ 1.62396361e+00  1.35192270e+00 -2.36751852e+00 -1.57586051e+00
 -7.32507269e-01 -4.95195434e-17 -1.00000000e+00  1.38896158e-16
 -4.69711808e-18  0.00000000e+00]


In [29]:
# recreate network
nt = Network()
# populates the nodes and edges data structures
nt.from_nx(network)
print(network.edges.data())
nt.show('docs/models/modularity.html')

[(0, 1, {'weight': 1, 'width': 1}), (1, 2, {'weight': 1, 'width': 1}), (1, 3, {'weight': 2, 'width': 1}), (3, 4, {'weight': 2, 'width': 1}), (3, 5, {'weight': 1, 'width': 1}), (3, 6, {'weight': 1, 'width': 1}), (4, 6, {'weight': 1, 'width': 1}), (5, 7, {'weight': 1, 'width': 1}), (5, 8, {'weight': 1, 'width': 1}), (5, 9, {'weight': 1, 'width': 1})]


### Calculate modularity using iGraph

In [30]:
from igraph import Graph

newGraph = Graph.from_networkx(network)
clusters = newGraph.community_leading_eigenvector(clusters=2)
print(clusters)

# loop and update cluster colors
for node in clusters[0]:
    network.update(nodes=[(node, {"label": "g1", "color": "green"})])
for node in clusters[1]:
    network.update(nodes=[(node, {"label": "g2", "color": "red"})])

Clustering with 10 elements and 2 clusters
[0] 0, 1, 2, 3, 4, 6
[1] 5, 7, 8, 9


In [31]:
# recreate network
nt = Network()
# populates the nodes and edges data structures
nt.from_nx(network)
print(network.edges.data())
nt.show('docs/models/modularity.html')

[(0, 1, {'weight': 1, 'width': 1}), (1, 2, {'weight': 1, 'width': 1}), (1, 3, {'weight': 2, 'width': 1}), (3, 4, {'weight': 2, 'width': 1}), (3, 5, {'weight': 1, 'width': 1}), (3, 6, {'weight': 1, 'width': 1}), (4, 6, {'weight': 1, 'width': 1}), (5, 7, {'weight': 1, 'width': 1}), (5, 8, {'weight': 1, 'width': 1}), (5, 9, {'weight': 1, 'width': 1})]
